CELL 1 — Imports

In [1]:
import pandas as pd
import requests
import time
from datetime import datetime
from tqdm import tqdm
import os

CELL 2 — Create Data Folder Path

In [2]:
DATA_DIR = "../data"

os.makedirs(DATA_DIR, exist_ok=True)

print("Data folder ready:", DATA_DIR)

Data folder ready: ../data

CELL 3 — Binance API Config

We use Binance because:

more stable
huge history
free
easy

In [3]:
SYMBOL = "BTCUSDT"
INTERVAL = "5m"

BASE_URL = "https://api.binance.com/api/v3/klines"

LIMIT = 1000

CELL 4 — Date Range

In [4]:
start_date = "2020-01-01"
end_date = "2026-01-01"

start_ts = int(pd.Timestamp(start_date).timestamp() * 1000)
end_ts = int(pd.Timestamp(end_date).timestamp() * 1000)

print(start_ts, end_ts)

1577836800000 1767225600000

CELL 5 — Download Function

In [5]:
def fetch_klines(symbol, interval, start_ts, end_ts, limit=1000):

    params = {
        "symbol": symbol,
        "interval": interval,
        "startTime": start_ts,
        "endTime": end_ts,
        "limit": limit
    }

    response = requests.get(BASE_URL, params=params)

    if response.status_code != 200:
        print("Error:", response.text)
        return []

    return response.json()

CELL 6 — Download All Historical Data

In [6]:
all_data = []

current_ts = start_ts

while current_ts < end_ts:

    data = fetch_klines(
        SYMBOL,
        INTERVAL,
        current_ts,
        end_ts,
        LIMIT
    )

    if not data:
        print("No more data.")
        break

    all_data.extend(data)

    last_open_time = data[-1][0]

    current_ts = last_open_time + 1

    print(
        "Downloaded candles:",
        len(all_data),
        "| Last:",
        datetime.fromtimestamp(last_open_time / 1000)
    )

    time.sleep(0.2)

print("Finished.")

Downloaded candles: 1000 | Last: 2020-01-04 16:45:00
Downloaded candles: 2000 | Last: 2020-01-08 04:05:00
Downloaded candles: 3000 | Last: 2020-01-11 15:25:00
Downloaded candles: 4000 | Last: 2020-01-15 02:45:00
Downloaded candles: 5000 | Last: 2020-01-18 14:05:00
Downloaded candles: 6000 | Last: 2020-01-22 01:25:00
Downloaded candles: 7000 | Last: 2020-01-25 12:45:00
Downloaded candles: 8000 | Last: 2020-01-29 00:05:00
Downloaded candles: 9000 | Last: 2020-02-01 11:25:00
Downloaded candles: 10000 | Last: 2020-02-04 22:45:00
Downloaded candles: 11000 | Last: 2020-02-08 10:05:00
Downloaded candles: 12000 | Last: 2020-02-11 22:25:00
Downloaded candles: 13000 | Last: 2020-02-15 09:45:00
Downloaded candles: 14000 | Last: 2020-02-18 21:05:00
Downloaded candles: 15000 | Last: 2020-02-22 14:15:00
Downloaded candles: 16000 | Last: 2020-02-26 01:35:00
Downloaded candles: 17000 | Last: 2020-02-29 12:55:00
Downloaded candles: 18000 | Last: 2020-03-04 00:15:00
Downloaded candles: 19000 | Last: 2020-03-07 13:40:00
Downloaded candles: 20000 | Last: 2020-03-11 01:00:00
Downloaded candles: 21000 | Last: 2020-03-14 12:20:00
Downloaded candles: 22000 | Last: 2020-03-17 23:40:00
Downloaded candles: 23000 | Last: 2020-03-21 11:00:00
Downloaded candles: 24000 | Last: 2020-03-24 22:20:00
Downloaded candles: 25000 | Last: 2020-03-28 09:40:00
Downloaded candles: 26000 | Last: 2020-03-31 21:00:00
Downloaded candles: 27000 | Last: 2020-04-04 08:20:00
Downloaded candles: 28000 | Last: 2020-04-07 19:40:00
Downloaded candles: 29000 | Last: 2020-04-11 07:00:00
Downloaded candles: 30000 | Last: 2020-04-14 18:20:00
Downloaded candles: 31000 | Last: 2020-04-18 05:40:00
Downloaded candles: 32000 | Last: 2020-04-21 17:00:00
Downloaded candles: 33000 | Last: 2020-04-25 04:20:00
Downloaded candles: 34000 | Last: 2020-04-28 18:10:00
Downloaded candles: 35000 | Last: 2020-05-02 05:30:00
Downloaded candles: 36000 | Last: 2020-05-05 16:50:00
Downloaded candles: 37000 | Last: 2020-05-09 04:10:00
Downloaded candles: 38000 | Last: 2020-05-12 15:30:00
Downloaded candles: 39000 | Last: 2020-05-16 02:50:00
Downloaded candles: 40000 | Last: 2020-05-19 14:10:00
Downloaded candles: 41000 | Last: 2020-05-23 01:30:00
Downloaded candles: 42000 | Last: 2020-05-26 12:50:00
Downloaded candles: 43000 | Last: 2020-05-30 00:10:00
Downloaded candles: 44000 | Last: 2020-06-02 11:30:00
Downloaded candles: 45000 | Last: 2020-06-05 22:50:00
Downloaded candles: 46000 | Last: 2020-06-09 10:10:00
Downloaded candles: 47000 | Last: 2020-06-12 21:30:00
Downloaded candles: 48000 | Last: 2020-06-16 08:50:00
Downloaded candles: 49000 | Last: 2020-06-19 20:10:00
Downloaded candles: 50000 | Last: 2020-06-23 07:30:00
Downloaded candles: 51000 | Last: 2020-06-26 18:50:00
Downloaded candles: 52000 | Last: 2020-06-30 09:40:00
Downloaded candles: 53000 | Last: 2020-07-03 21:00:00
Downloaded candles: 54000 | Last: 2020-07-07 08:20:00
Downloaded candles: 55000 | Last: 2020-07-10 19:40:00
Downloaded candles: 56000 | Last: 2020-07-14 07:00:00
Downloaded candles: 57000 | Last: 2020-07-17 18:20:00
Downloaded candles: 58000 | Last: 2020-07-21 05:40:00
Downloaded candles: 59000 | Last: 2020-07-24 17:00:00
Downloaded candles: 60000 | Last: 2020-07-28 04:20:00
Downloaded candles: 61000 | Last: 2020-07-31 15:40:00
Downloaded candles: 62000 | Last: 2020-08-04 03:00:00
Downloaded candles: 63000 | Last: 2020-08-07 14:20:00
Downloaded candles: 64000 | Last: 2020-08-11 01:40:00
Downloaded candles: 65000 | Last: 2020-08-14 13:00:00
Downloaded candles: 66000 | Last: 2020-08-18 00:20:00
Downloaded candles: 67000 | Last: 2020-08-21 11:40:00
Downloaded candles: 68000 | Last: 2020-08-24 23:00:00
Downloaded candles: 69000 | Last: 2020-08-28 10:20:00
Downloaded candles: 70000 | Last: 2020-08-31 21:40:00
Downloaded candles: 71000 | Last: 2020-09-04 09:00:00
Downloaded candles: 72000 | Last: 2020-09-07 20:20:00
Downloaded candles: 73000 | Last: 2020-09-11 07:40:00
Downloaded candles: 74000 | Last: 2020-09-14 19:00:00
Downloaded candles: 75000 | Last: 2020-09-18 06:20:00
Downloaded candles: 76000 | Last: 2020-09-21 17:40:00
Downloaded candles: 77000 | Last: 2020-09-25 05:00:00
Downloaded candles: 78000 | Last: 2020-09-28 16:20:00
Downloaded candles: 79000 | Last: 2020-10-02 03:40:00
Downloaded candles: 80000 | Last: 2020-10-05 15:00:00
Downloaded candles: 81000 | Last: 2020-10-09 02:20:00
Downloaded candles: 82000 | Last: 2020-10-12 13:40:00
Downloaded candles: 83000 | Last: 2020-10-16 01:00:00
Downloaded candles: 84000 | Last: 2020-10-19 12:20:00
Downloaded candles: 85000 | Last: 2020-10-22 23:40:00
Downloaded candles: 86000 | Last: 2020-10-26 11:00:00
Downloaded candles: 87000 | Last: 2020-10-29 22:20:00
Downloaded candles: 88000 | Last: 2020-11-02 09:40:00
Downloaded candles: 89000 | Last: 2020-11-05 21:00:00
Downloaded candles: 90000 | Last: 2020-11-09 08:20:00
Downloaded candles: 91000 | Last: 2020-11-12 19:40:00
Downloaded candles: 92000 | Last: 2020-11-16 07:00:00
Downloaded candles: 93000 | Last: 2020-11-19 18:20:00
Downloaded candles: 94000 | Last: 2020-11-23 05:40:00
Downloaded candles: 95000 | Last: 2020-11-26 17:00:00
Downloaded candles: 96000 | Last: 2020-11-30 04:20:00
Downloaded candles: 97000 | Last: 2020-12-03 16:40:00
Downloaded candles: 98000 | Last: 2020-12-07 04:00:00
Downloaded candles: 99000 | Last: 2020-12-10 15:20:00
Downloaded candles: 100000 | Last: 2020-12-14 02:40:00
Downloaded candles: 101000 | Last: 2020-12-17 14:00:00
Downloaded candles: 102000 | Last: 2020-12-21 01:20:00
Downloaded candles: 103000 | Last: 2020-12-24 16:50:00
Downloaded candles: 104000 | Last: 2020-12-28 05:10:00
Downloaded candles: 105000 | Last: 2020-12-31 16:30:00
Downloaded candles: 106000 | Last: 2021-01-04 03:50:00
Downloaded candles: 107000 | Last: 2021-01-07 15:10:00
Downloaded candles: 108000 | Last: 2021-01-11 02:30:00
Downloaded candles: 109000 | Last: 2021-01-14 13:50:00
Downloaded candles: 110000 | Last: 2021-01-18 01:10:00
Downloaded candles: 111000 | Last: 2021-01-21 12:30:00
Downloaded candles: 112000 | Last: 2021-01-24 23:50:00
Downloaded candles: 113000 | Last: 2021-01-28 11:10:00
Downloaded candles: 114000 | Last: 2021-01-31 22:30:00
Downloaded candles: 115000 | Last: 2021-02-04 09:50:00
Downloaded candles: 116000 | Last: 2021-02-07 21:10:00
Downloaded candles: 117000 | Last: 2021-02-11 08:30:00
Downloaded candles: 118000 | Last: 2021-02-14 21:05:00
Downloaded candles: 119000 | Last: 2021-02-18 08:25:00
Downloaded candles: 120000 | Last: 2021-02-21 19:45:00
Downloaded candles: 121000 | Last: 2021-02-25 07:05:00
Downloaded candles: 122000 | Last: 2021-02-28 18:25:00
Downloaded candles: 123000 | Last: 2021-03-04 05:45:00
Downloaded candles: 124000 | Last: 2021-03-07 18:35:00
Downloaded candles: 125000 | Last: 2021-03-11 05:55:00
Downloaded candles: 126000 | Last: 2021-03-14 17:15:00
Downloaded candles: 127000 | Last: 2021-03-18 04:35:00
Downloaded candles: 128000 | Last: 2021-03-21 15:55:00
Downloaded candles: 129000 | Last: 2021-03-25 03:15:00
Downloaded candles: 130000 | Last: 2021-03-28 14:35:00
Downloaded candles: 131000 | Last: 2021-04-01 01:55:00
Downloaded candles: 132000 | Last: 2021-04-04 13:15:00
Downloaded candles: 133000 | Last: 2021-04-08 00:35:00
Downloaded candles: 134000 | Last: 2021-04-11 11:55:00
Downloaded candles: 135000 | Last: 2021-04-14 23:15:00
Downloaded candles: 136000 | Last: 2021-04-18 10:35:00
Downloaded candles: 137000 | Last: 2021-04-22 00:25:00
Downloaded candles: 138000 | Last: 2021-04-25 16:25:00
Downloaded candles: 139000 | Last: 2021-04-29 03:45:00
Downloaded candles: 140000 | Last: 2021-05-02 15:05:00
Downloaded candles: 141000 | Last: 2021-05-06 02:25:00
Downloaded candles: 142000 | Last: 2021-05-09 13:45:00
Downloaded candles: 143000 | Last: 2021-05-13 01:05:00
Downloaded candles: 144000 | Last: 2021-05-16 12:25:00
Downloaded candles: 145000 | Last: 2021-05-19 23:45:00
Downloaded candles: 146000 | Last: 2021-05-23 11:05:00
Downloaded candles: 147000 | Last: 2021-05-26 22:25:00
Downloaded candles: 148000 | Last: 2021-05-30 09:45:00
Downloaded candles: 149000 | Last: 2021-06-02 21:05:00
Downloaded candles: 150000 | Last: 2021-06-06 08:25:00
Downloaded candles: 151000 | Last: 2021-06-09 19:45:00
Downloaded candles: 152000 | Last: 2021-06-13 07:05:00
Downloaded candles: 153000 | Last: 2021-06-16 18:25:00
Downloaded candles: 154000 | Last: 2021-06-20 05:45:00
Downloaded candles: 155000 | Last: 2021-06-23 17:05:00
Downloaded candles: 156000 | Last: 2021-06-27 04:25:00
Downloaded candles: 157000 | Last: 2021-06-30 15:45:00
Downloaded candles: 158000 | Last: 2021-07-04 03:05:00
Downloaded candles: 159000 | Last: 2021-07-07 14:25:00
Downloaded candles: 160000 | Last: 2021-07-11 01:45:00
Downloaded candles: 161000 | Last: 2021-07-14 13:05:00
Downloaded candles: 162000 | Last: 2021-07-18 00:25:00
Downloaded candles: 163000 | Last: 2021-07-21 11:45:00
Downloaded candles: 164000 | Last: 2021-07-24 23:05:00
Downloaded candles: 165000 | Last: 2021-07-28 10:25:00
Downloaded candles: 166000 | Last: 2021-07-31 21:45:00
Downloaded candles: 167000 | Last: 2021-08-04 09:05:00
Downloaded candles: 168000 | Last: 2021-08-07 20:25:00
Downloaded candles: 169000 | Last: 2021-08-11 07:45:00
Downloaded candles: 170000 | Last: 2021-08-14 23:35:00
Downloaded candles: 171000 | Last: 2021-08-18 10:55:00
Downloaded candles: 172000 | Last: 2021-08-21 22:15:00
Downloaded candles: 173000 | Last: 2021-08-25 09:35:00
Downloaded candles: 174000 | Last: 2021-08-28 20:55:00
Downloaded candles: 175000 | Last: 2021-09-01 08:15:00
Downloaded candles: 176000 | Last: 2021-09-04 19:35:00
Downloaded candles: 177000 | Last: 2021-09-08 06:55:00
Downloaded candles: 178000 | Last: 2021-09-11 18:15:00
Downloaded candles: 179000 | Last: 2021-09-15 05:35:00
Downloaded candles: 180000 | Last: 2021-09-18 16:55:00
Downloaded candles: 181000 | Last: 2021-09-22 04:15:00
Downloaded candles: 182000 | Last: 2021-09-25 15:35:00
Downloaded candles: 183000 | Last: 2021-09-29 02:55:00
Downloaded candles: 184000 | Last: 2021-10-02 16:15:00
Downloaded candles: 185000 | Last: 2021-10-06 03:35:00
Downloaded candles: 186000 | Last: 2021-10-09 14:55:00
Downloaded candles: 187000 | Last: 2021-10-13 02:15:00
Downloaded candles: 188000 | Last: 2021-10-16 13:35:00
Downloaded candles: 189000 | Last: 2021-10-20 00:55:00
Downloaded candles: 190000 | Last: 2021-10-23 12:15:00
Downloaded candles: 191000 | Last: 2021-10-26 23:35:00
Downloaded candles: 192000 | Last: 2021-10-30 10:55:00
Downloaded candles: 193000 | Last: 2021-11-02 22:15:00
Downloaded candles: 194000 | Last: 2021-11-06 09:35:00
Downloaded candles: 195000 | Last: 2021-11-09 20:55:00
Downloaded candles: 196000 | Last: 2021-11-13 08:15:00
Downloaded candles: 197000 | Last: 2021-11-16 19:35:00
Downloaded candles: 198000 | Last: 2021-11-20 06:55:00
Downloaded candles: 199000 | Last: 2021-11-23 18:15:00
Downloaded candles: 200000 | Last: 2021-11-27 05:35:00
Downloaded candles: 201000 | Last: 2021-11-30 16:55:00
Downloaded candles: 202000 | Last: 2021-12-04 04:15:00
Downloaded candles: 203000 | Last: 2021-12-07 15:35:00
Downloaded candles: 204000 | Last: 2021-12-11 02:55:00
Downloaded candles: 205000 | Last: 2021-12-14 14:15:00
Downloaded candles: 206000 | Last: 2021-12-18 01:35:00
Downloaded candles: 207000 | Last: 2021-12-21 12:55:00
Downloaded candles: 208000 | Last: 2021-12-25 00:15:00
Downloaded candles: 209000 | Last: 2021-12-28 11:35:00
Downloaded candles: 210000 | Last: 2021-12-31 22:55:00
Downloaded candles: 211000 | Last: 2022-01-04 10:15:00
Downloaded candles: 212000 | Last: 2022-01-07 21:35:00
Downloaded candles: 213000 | Last: 2022-01-11 08:55:00
Downloaded candles: 214000 | Last: 2022-01-14 20:15:00
Downloaded candles: 215000 | Last: 2022-01-18 07:35:00
Downloaded candles: 216000 | Last: 2022-01-21 18:55:00
Downloaded candles: 217000 | Last: 2022-01-25 06:15:00
Downloaded candles: 218000 | Last: 2022-01-28 17:35:00
Downloaded candles: 219000 | Last: 2022-02-01 04:55:00
Downloaded candles: 220000 | Last: 2022-02-04 16:15:00
Downloaded candles: 221000 | Last: 2022-02-08 03:35:00
Downloaded candles: 222000 | Last: 2022-02-11 14:55:00
Downloaded candles: 223000 | Last: 2022-02-15 02:15:00
Downloaded candles: 224000 | Last: 2022-02-18 13:35:00
Downloaded candles: 225000 | Last: 2022-02-22 00:55:00
Downloaded candles: 226000 | Last: 2022-02-25 12:15:00
Downloaded candles: 227000 | Last: 2022-02-28 23:35:00
Downloaded candles: 228000 | Last: 2022-03-04 10:55:00
Downloaded candles: 229000 | Last: 2022-03-07 22:15:00
Downloaded candles: 230000 | Last: 2022-03-11 09:35:00
Downloaded candles: 231000 | Last: 2022-03-14 20:55:00
Downloaded candles: 232000 | Last: 2022-03-18 08:15:00
Downloaded candles: 233000 | Last: 2022-03-21 19:35:00
Downloaded candles: 234000 | Last: 2022-03-25 06:55:00
Downloaded candles: 235000 | Last: 2022-03-28 18:15:00
Downloaded candles: 236000 | Last: 2022-04-01 05:35:00
Downloaded candles: 237000 | Last: 2022-04-04 16:55:00
Downloaded candles: 238000 | Last: 2022-04-08 04:15:00
Downloaded candles: 239000 | Last: 2022-04-11 15:35:00
Downloaded candles: 240000 | Last: 2022-04-15 02:55:00
Downloaded candles: 241000 | Last: 2022-04-18 14:15:00
Downloaded candles: 242000 | Last: 2022-04-22 01:35:00
Downloaded candles: 243000 | Last: 2022-04-25 12:55:00
Downloaded candles: 244000 | Last: 2022-04-29 00:15:00
Downloaded candles: 245000 | Last: 2022-05-02 11:35:00
Downloaded candles: 246000 | Last: 2022-05-05 22:55:00
Downloaded candles: 247000 | Last: 2022-05-09 10:15:00
Downloaded candles: 248000 | Last: 2022-05-12 21:35:00
Downloaded candles: 249000 | Last: 2022-05-16 08:55:00
Downloaded candles: 250000 | Last: 2022-05-19 20:15:00
Downloaded candles: 251000 | Last: 2022-05-23 07:35:00
Downloaded candles: 252000 | Last: 2022-05-26 18:55:00
Downloaded candles: 253000 | Last: 2022-05-30 06:15:00
Downloaded candles: 254000 | Last: 2022-06-02 17:35:00
Downloaded candles: 255000 | Last: 2022-06-06 04:55:00
Downloaded candles: 256000 | Last: 2022-06-09 16:15:00
Downloaded candles: 257000 | Last: 2022-06-13 03:35:00
Downloaded candles: 258000 | Last: 2022-06-16 14:55:00
Downloaded candles: 259000 | Last: 2022-06-20 02:15:00
Downloaded candles: 260000 | Last: 2022-06-23 13:35:00
Downloaded candles: 261000 | Last: 2022-06-27 00:55:00
Downloaded candles: 262000 | Last: 2022-06-30 12:15:00
Downloaded candles: 263000 | Last: 2022-07-03 23:35:00
Downloaded candles: 264000 | Last: 2022-07-07 10:55:00
Downloaded candles: 265000 | Last: 2022-07-10 22:15:00
Downloaded candles: 266000 | Last: 2022-07-14 09:35:00
Downloaded candles: 267000 | Last: 2022-07-17 20:55:00
Downloaded candles: 268000 | Last: 2022-07-21 08:15:00
Downloaded candles: 269000 | Last: 2022-07-24 19:35:00
Downloaded candles: 270000 | Last: 2022-07-28 06:55:00
Downloaded candles: 271000 | Last: 2022-07-31 18:15:00
Downloaded candles: 272000 | Last: 2022-08-04 05:35:00
Downloaded candles: 273000 | Last: 2022-08-07 16:55:00
Downloaded candles: 274000 | Last: 2022-08-11 04:15:00
Downloaded candles: 275000 | Last: 2022-08-14 15:35:00
Downloaded candles: 276000 | Last: 2022-08-18 02:55:00
Downloaded candles: 277000 | Last: 2022-08-21 14:15:00
Downloaded candles: 278000 | Last: 2022-08-25 01:35:00
Downloaded candles: 279000 | Last: 2022-08-28 12:55:00
Downloaded candles: 280000 | Last: 2022-09-01 00:15:00
Downloaded candles: 281000 | Last: 2022-09-04 11:35:00
Downloaded candles: 282000 | Last: 2022-09-07 22:55:00
Downloaded candles: 283000 | Last: 2022-09-11 10:15:00
Downloaded candles: 284000 | Last: 2022-09-14 21:35:00
Downloaded candles: 285000 | Last: 2022-09-18 08:55:00
Downloaded candles: 286000 | Last: 2022-09-21 20:15:00
Downloaded candles: 287000 | Last: 2022-09-25 07:35:00
Downloaded candles: 288000 | Last: 2022-09-28 18:55:00
Downloaded candles: 289000 | Last: 2022-10-02 06:15:00
Downloaded candles: 290000 | Last: 2022-10-05 17:35:00
Downloaded candles: 291000 | Last: 2022-10-09 04:55:00
Downloaded candles: 292000 | Last: 2022-10-12 16:15:00
Downloaded candles: 293000 | Last: 2022-10-16 03:35:00
Downloaded candles: 294000 | Last: 2022-10-19 14:55:00
Downloaded candles: 295000 | Last: 2022-10-23 02:15:00
Downloaded candles: 296000 | Last: 2022-10-26 13:35:00
Downloaded candles: 297000 | Last: 2022-10-30 00:55:00
Downloaded candles: 298000 | Last: 2022-11-02 12:15:00
Downloaded candles: 299000 | Last: 2022-11-05 23:35:00
Downloaded candles: 300000 | Last: 2022-11-09 10:55:00
Downloaded candles: 301000 | Last: 2022-11-12 22:15:00
Downloaded candles: 302000 | Last: 2022-11-16 09:35:00
Downloaded candles: 303000 | Last: 2022-11-19 20:55:00
Downloaded candles: 304000 | Last: 2022-11-23 08:15:00
Downloaded candles: 305000 | Last: 2022-11-26 19:35:00
Downloaded candles: 306000 | Last: 2022-11-30 06:55:00
Downloaded candles: 307000 | Last: 2022-12-03 18:15:00
Downloaded candles: 308000 | Last: 2022-12-07 05:35:00
Downloaded candles: 309000 | Last: 2022-12-10 16:55:00
Downloaded candles: 310000 | Last: 2022-12-14 04:15:00
Downloaded candles: 311000 | Last: 2022-12-17 15:35:00
Downloaded candles: 312000 | Last: 2022-12-21 02:55:00
Downloaded candles: 313000 | Last: 2022-12-24 14:15:00
Downloaded candles: 314000 | Last: 2022-12-28 01:35:00
Downloaded candles: 315000 | Last: 2022-12-31 12:55:00
Downloaded candles: 316000 | Last: 2023-01-04 00:15:00
Downloaded candles: 317000 | Last: 2023-01-07 11:35:00
Downloaded candles: 318000 | Last: 2023-01-10 22:55:00
Downloaded candles: 319000 | Last: 2023-01-14 10:15:00
Downloaded candles: 320000 | Last: 2023-01-17 21:35:00
Downloaded candles: 321000 | Last: 2023-01-21 08:55:00
Downloaded candles: 322000 | Last: 2023-01-24 20:15:00
Downloaded candles: 323000 | Last: 2023-01-28 07:35:00
Downloaded candles: 324000 | Last: 2023-01-31 18:55:00
Downloaded candles: 325000 | Last: 2023-02-04 06:15:00
Downloaded candles: 326000 | Last: 2023-02-07 17:35:00
Downloaded candles: 327000 | Last: 2023-02-11 04:55:00
Downloaded candles: 328000 | Last: 2023-02-14 16:15:00
Downloaded candles: 329000 | Last: 2023-02-18 03:35:00
Downloaded candles: 330000 | Last: 2023-02-21 14:55:00
Downloaded candles: 331000 | Last: 2023-02-25 02:15:00
Downloaded candles: 332000 | Last: 2023-02-28 13:35:00
Downloaded candles: 333000 | Last: 2023-03-04 00:55:00
Downloaded candles: 334000 | Last: 2023-03-07 12:15:00
Downloaded candles: 335000 | Last: 2023-03-10 23:35:00
Downloaded candles: 336000 | Last: 2023-03-14 10:55:00
Downloaded candles: 337000 | Last: 2023-03-17 22:15:00
Downloaded candles: 338000 | Last: 2023-03-21 09:35:00
Downloaded candles: 339000 | Last: 2023-03-24 22:15:00
Downloaded candles: 340000 | Last: 2023-03-28 09:35:00
Downloaded candles: 341000 | Last: 2023-03-31 20:55:00
Downloaded candles: 342000 | Last: 2023-04-04 08:15:00
Downloaded candles: 343000 | Last: 2023-04-07 19:35:00
Downloaded candles: 344000 | Last: 2023-04-11 06:55:00
Downloaded candles: 345000 | Last: 2023-04-14 18:15:00
Downloaded candles: 346000 | Last: 2023-04-18 05:35:00
Downloaded candles: 347000 | Last: 2023-04-21 16:55:00
Downloaded candles: 348000 | Last: 2023-04-25 04:15:00
Downloaded candles: 349000 | Last: 2023-04-28 15:35:00
Downloaded candles: 350000 | Last: 2023-05-02 02:55:00
Downloaded candles: 351000 | Last: 2023-05-05 14:15:00
Downloaded candles: 352000 | Last: 2023-05-09 01:35:00
Downloaded candles: 353000 | Last: 2023-05-12 12:55:00
Downloaded candles: 354000 | Last: 2023-05-16 00:15:00
Downloaded candles: 355000 | Last: 2023-05-19 11:35:00
Downloaded candles: 356000 | Last: 2023-05-22 22:55:00
Downloaded candles: 357000 | Last: 2023-05-26 10:15:00
Downloaded candles: 358000 | Last: 2023-05-29 21:35:00
Downloaded candles: 359000 | Last: 2023-06-02 08:55:00
Downloaded candles: 360000 | Last: 2023-06-05 20:15:00
Downloaded candles: 361000 | Last: 2023-06-09 07:35:00
Downloaded candles: 362000 | Last: 2023-06-12 18:55:00
Downloaded candles: 363000 | Last: 2023-06-16 06:15:00
Downloaded candles: 364000 | Last: 2023-06-19 17:35:00
Downloaded candles: 365000 | Last: 2023-06-23 04:55:00

CELL 7 — Convert to DataFrame

In [7]:
columns = [
    "open_time",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "close_time",
    "quote_asset_volume",
    "number_of_trades",
    "taker_buy_base_volume",
    "taker_buy_quote_volume",
    "ignore"
]

df = pd.DataFrame(all_data, columns=columns)

df.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_volume,taker_buy_quote_volume,ignore
0,1577836800000,7195.24000000,7196.25000000,7178.64000000,7179.78000000,95.50913300,1577837099999,686317.13625177,1127,32.77324500,235537.29504531,0
1,1577837100000,7179.76000000,7191.77000000,7178.20000000,7191.07000000,59.36522500,1577837399999,426481.26036406,631,24.76651300,177935.61820100,0
2,1577837400000,7193.15000000,7193.53000000,7180.24000000,7180.97000000,48.06851000,1577837699999,345446.50301879,694,19.42228300,139596.62168263,0
3,1577837700000,7180.97000000,7186.40000000,7177.35000000,7178.29000000,32.19292900,1577837999999,231162.55542356,576,12.96325800,93091.43327629,0
4,1577838000000,7177.71000000,7182.46000000,7175.47000000,7176.96000000,49.02739700,1577838299999,351927.89388145,710,22.81974400,163817.88115474,0

CELL 8 — Clean Data

In [8]:
numeric_cols = [
    "open",
    "high",
    "low",
    "close",
    "volume"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col])

df["datetime"] = pd.to_datetime(df["open_time"], unit="ms")

df = df[
    [
        "datetime",
        "open",
        "high",
        "low",
        "close",
        "volume"
    ]
]

df.head()

             datetime     open     high      low    close     volume
0 2020-01-01 00:00:00  7195.24  7196.25  7178.64  7179.78  95.509133
1 2020-01-01 00:05:00  7179.76  7191.77  7178.20  7191.07  59.365225
2 2020-01-01 00:10:00  7193.15  7193.53  7180.24  7180.97  48.068510
3 2020-01-01 00:15:00  7180.97  7186.40  7177.35  7178.29  32.192929
4 2020-01-01 00:20:00  7177.71  7182.46  7175.47  7176.96  49.027397

CELL 9 — Save CSV

In [9]:
csv_path = f"{DATA_DIR}/btcusdt_5m_2020_2026.csv"

df.to_csv(csv_path, index=False)

print("CSV Saved:", csv_path)

CSV Saved: ../data/btcusdt_5m_2020_2026.csv

CELL 10 — Save Faster Parquet File

In [10]:
parquet_path = f"{DATA_DIR}/btcusdt_5m_2020_2026.parquet"

df.to_parquet(parquet_path, index=False)

print("Parquet Saved:", parquet_path)

Parquet Saved: ../data/btcusdt_5m_2020_2026.parquet

CELL 11 — Final Dataset Info

In [11]:
print(df.shape)

df.tail()

(630831, 6)

                  datetime      open      high       low     close    volume
630826 2025-12-31 23:40:00  87652.46  87686.09  87652.46  87685.31  10.47354
630827 2025-12-31 23:45:00  87685.31  87697.40  87663.92  87690.61  13.07752
630828 2025-12-31 23:50:00  87690.60  87690.61  87641.14  87641.14  13.66626
630829 2025-12-31 23:55:00  87641.15  87655.31  87641.14  87648.22  18.20491
630830 2026-01-01 00:00:00  87648.21  87701.91  87632.74  87701.91  18.44460